[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
EXE_NAME = "ramon-client"
OUTPUT_PATH = "%CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY%\\output"

[env.development]
TARGET_PATH = "target\\debug"

[env.production]
TARGET_PATH = "target\\release"
BUILD_FLAGS = "--release"

[tasks.format]
command = "cargo"
args = ["fmt"]
toolchain = "nightly"

[tasks.build-client]
dependencies = []
script = [
    "cargo b %BUILD_FLAGS%"
]

[tasks.copy]
script = [
    "IF not exist %OUTPUT_PATH% (mkdir %OUTPUT_PATH%)",
    "COPY %CARGO_MAKE_CRATE_TARGET_DIRECTORY%\\debug\\%EXE_NAME%.exe %CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY%\\..\\output\\",
]

[tasks.all]
dependencies = ["build-client", "copy"]

[tasks.rebuild]
script = [
    "cargo clean",
    "cargo make all"
]