/* automatically generated by rust-bindgen 0.59.0 */

pub const RPC_C_AUTHN_WINNT: u32 = 10;
pub const FWP_ACTION_BLOCK: u32 = 4097;
pub const FWP_ACTION_PERMIT: u32 = 4098;
pub type wchar_t = ::std::os::raw::c_ushort;
pub type ULONG = ::std::os::raw::c_ulong;
pub type WINBOOL = ::std::os::raw::c_int;
pub type BYTE = ::std::os::raw::c_uchar;
pub type DWORD = ::std::os::raw::c_ulong;
pub type INT8 = ::std::os::raw::c_schar;
pub type INT16 = ::std::os::raw::c_short;
pub type INT32 = ::std::os::raw::c_int;
pub type INT64 = ::std::os::raw::c_longlong;
pub type UINT8 = ::std::os::raw::c_uchar;
pub type UINT16 = ::std::os::raw::c_ushort;
pub type UINT32 = ::std::os::raw::c_uint;
pub type UINT64 = ::std::os::raw::c_ulonglong;
pub type PVOID = *mut ::std::os::raw::c_void;
pub type WCHAR = wchar_t;
pub type LPWSTR = *mut WCHAR;
pub type HANDLE = PVOID;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _GUID {
    pub Data1: ::std::os::raw::c_ulong,
    pub Data2: ::std::os::raw::c_ushort,
    pub Data3: ::std::os::raw::c_ushort,
    pub Data4: [::std::os::raw::c_uchar; 8usize],
}
pub type GUID = _GUID;
pub type PSECURITY_DESCRIPTOR = PVOID;
pub type PSID = PVOID;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _SID_IDENTIFIER_AUTHORITY {
    pub Value: [BYTE; 6usize],
}
pub type SID_IDENTIFIER_AUTHORITY = _SID_IDENTIFIER_AUTHORITY;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _SID {
    pub Revision: BYTE,
    pub SubAuthorityCount: BYTE,
    pub IdentifierAuthority: SID_IDENTIFIER_AUTHORITY,
    pub SubAuthority: [DWORD; 1usize],
}
pub type SID = _SID;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _SID_AND_ATTRIBUTES {
    pub Sid: PSID,
    pub Attributes: DWORD,
}
pub type PSID_AND_ATTRIBUTES = *mut _SID_AND_ATTRIBUTES;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _SEC_WINNT_AUTH_IDENTITY_W {
    pub User: *mut ::std::os::raw::c_ushort,
    pub UserLength: ::std::os::raw::c_ulong,
    pub Domain: *mut ::std::os::raw::c_ushort,
    pub DomainLength: ::std::os::raw::c_ulong,
    pub Password: *mut ::std::os::raw::c_ushort,
    pub PasswordLength: ::std::os::raw::c_ulong,
    pub Flags: ::std::os::raw::c_ulong,
}
pub type SEC_WINNT_AUTH_IDENTITY_W = _SEC_WINNT_AUTH_IDENTITY_W;
pub type FWP_ACTION_TYPE = UINT32;
pub const FWP_DATA_TYPE__FWP_EMPTY: FWP_DATA_TYPE_ = 0;
pub const FWP_DATA_TYPE__FWP_UINT8: FWP_DATA_TYPE_ = 1;
pub const FWP_DATA_TYPE__FWP_UINT16: FWP_DATA_TYPE_ = 2;
pub const FWP_DATA_TYPE__FWP_UINT32: FWP_DATA_TYPE_ = 3;
pub const FWP_DATA_TYPE__FWP_UINT64: FWP_DATA_TYPE_ = 4;
pub const FWP_DATA_TYPE__FWP_INT8: FWP_DATA_TYPE_ = 5;
pub const FWP_DATA_TYPE__FWP_INT16: FWP_DATA_TYPE_ = 6;
pub const FWP_DATA_TYPE__FWP_INT32: FWP_DATA_TYPE_ = 7;
pub const FWP_DATA_TYPE__FWP_INT64: FWP_DATA_TYPE_ = 8;
pub const FWP_DATA_TYPE__FWP_FLOAT: FWP_DATA_TYPE_ = 9;
pub const FWP_DATA_TYPE__FWP_DOUBLE: FWP_DATA_TYPE_ = 10;
pub const FWP_DATA_TYPE__FWP_BYTE_ARRAY16_TYPE: FWP_DATA_TYPE_ = 11;
pub const FWP_DATA_TYPE__FWP_BYTE_BLOB_TYPE: FWP_DATA_TYPE_ = 12;
pub const FWP_DATA_TYPE__FWP_SID: FWP_DATA_TYPE_ = 13;
pub const FWP_DATA_TYPE__FWP_SECURITY_DESCRIPTOR_TYPE: FWP_DATA_TYPE_ = 14;
pub const FWP_DATA_TYPE__FWP_TOKEN_INFORMATION_TYPE: FWP_DATA_TYPE_ = 15;
pub const FWP_DATA_TYPE__FWP_TOKEN_ACCESS_INFORMATION_TYPE: FWP_DATA_TYPE_ = 16;
pub const FWP_DATA_TYPE__FWP_UNICODE_STRING_TYPE: FWP_DATA_TYPE_ = 17;
pub const FWP_DATA_TYPE__FWP_BYTE_ARRAY6_TYPE: FWP_DATA_TYPE_ = 18;
pub const FWP_DATA_TYPE__FWP_SINGLE_DATA_TYPE_MAX: FWP_DATA_TYPE_ = 255;
pub const FWP_DATA_TYPE__FWP_V4_ADDR_MASK: FWP_DATA_TYPE_ = 256;
pub const FWP_DATA_TYPE__FWP_V6_ADDR_MASK: FWP_DATA_TYPE_ = 257;
pub const FWP_DATA_TYPE__FWP_RANGE_TYPE: FWP_DATA_TYPE_ = 258;
pub const FWP_DATA_TYPE__FWP_DATA_TYPE_MAX: FWP_DATA_TYPE_ = 259;
pub type FWP_DATA_TYPE_ = ::std::os::raw::c_uint;
pub use self::FWP_DATA_TYPE_ as FWP_DATA_TYPE;
pub const FWP_MATCH_TYPE__FWP_MATCH_EQUAL: FWP_MATCH_TYPE_ = 0;
pub const FWP_MATCH_TYPE__FWP_MATCH_GREATER: FWP_MATCH_TYPE_ = 1;
pub const FWP_MATCH_TYPE__FWP_MATCH_LESS: FWP_MATCH_TYPE_ = 2;
pub const FWP_MATCH_TYPE__FWP_MATCH_GREATER_OR_EQUAL: FWP_MATCH_TYPE_ = 3;
pub const FWP_MATCH_TYPE__FWP_MATCH_LESS_OR_EQUAL: FWP_MATCH_TYPE_ = 4;
pub const FWP_MATCH_TYPE__FWP_MATCH_RANGE: FWP_MATCH_TYPE_ = 5;
pub const FWP_MATCH_TYPE__FWP_MATCH_FLAGS_ALL_SET: FWP_MATCH_TYPE_ = 6;
pub const FWP_MATCH_TYPE__FWP_MATCH_FLAGS_ANY_SET: FWP_MATCH_TYPE_ = 7;
pub const FWP_MATCH_TYPE__FWP_MATCH_FLAGS_NONE_SET: FWP_MATCH_TYPE_ = 8;
pub const FWP_MATCH_TYPE__FWP_MATCH_EQUAL_CASE_INSENSITIVE: FWP_MATCH_TYPE_ = 9;
pub const FWP_MATCH_TYPE__FWP_MATCH_NOT_EQUAL: FWP_MATCH_TYPE_ = 10;
pub const FWP_MATCH_TYPE__FWP_MATCH_TYPE_MAX: FWP_MATCH_TYPE_ = 11;
pub type FWP_MATCH_TYPE_ = ::std::os::raw::c_uint;
pub use self::FWP_MATCH_TYPE_ as FWP_MATCH_TYPE;
pub const FWP_FILTER_ENUM_TYPE__FWP_FILTER_ENUM_FULLY_CONTAINED: FWP_FILTER_ENUM_TYPE_ = 0;
pub const FWP_FILTER_ENUM_TYPE__FWP_FILTER_ENUM_OVERLAPPING: FWP_FILTER_ENUM_TYPE_ = 1;
pub const FWP_FILTER_ENUM_TYPE__FWP_FILTER_ENUM_TYPE_MAX: FWP_FILTER_ENUM_TYPE_ = 2;
pub type FWP_FILTER_ENUM_TYPE_ = ::std::os::raw::c_uint;
pub use self::FWP_FILTER_ENUM_TYPE_ as FWP_FILTER_ENUM_TYPE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FWP_BYTE_ARRAY6_ {
    pub byteArray6: [UINT8; 6usize],
}
pub type FWP_BYTE_ARRAY6 = FWP_BYTE_ARRAY6_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FWP_BYTE_ARRAY16_ {
    pub byteArray16: [UINT8; 16usize],
}
pub type FWP_BYTE_ARRAY16 = FWP_BYTE_ARRAY16_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FWP_BYTE_BLOB_ {
    pub size: UINT32,
    pub data: *mut UINT8,
}
pub type FWP_BYTE_BLOB = FWP_BYTE_BLOB_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FWP_TOKEN_INFORMATION_ {
    pub sidCount: ULONG,
    pub sids: PSID_AND_ATTRIBUTES,
    pub restrictedSidCount: ULONG,
    pub restrictedSids: PSID_AND_ATTRIBUTES,
}
pub type FWP_TOKEN_INFORMATION = FWP_TOKEN_INFORMATION_;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FWP_VALUE0_ {
    pub type_: FWP_DATA_TYPE,
    pub __bindgen_anon_1: FWP_VALUE0___bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FWP_VALUE0___bindgen_ty_1 {
    pub uint8: UINT8,
    pub uint16: UINT16,
    pub uint32: UINT32,
    pub uint64: *mut UINT64,
    pub int8: INT8,
    pub int16: INT16,
    pub int32: INT32,
    pub int64: *mut INT64,
    pub float32: f32,
    pub double64: *mut f64,
    pub byteArray16: *mut FWP_BYTE_ARRAY16,
    pub byteBlob: *mut FWP_BYTE_BLOB,
    pub sid: *mut SID,
    pub sd: *mut FWP_BYTE_BLOB,
    pub tokenInformation: *mut FWP_TOKEN_INFORMATION,
    pub tokenAccessInformation: *mut FWP_BYTE_BLOB,
    pub unicodeString: LPWSTR,
    pub byteArray6: *mut FWP_BYTE_ARRAY6,
}
pub type FWP_VALUE0 = FWP_VALUE0_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FWP_V4_ADDR_AND_MASK_ {
    pub addr: UINT32,
    pub mask: UINT32,
}
pub type FWP_V4_ADDR_AND_MASK = FWP_V4_ADDR_AND_MASK_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FWP_V6_ADDR_AND_MASK_ {
    pub addr: [UINT8; 16usize],
    pub prefixLength: UINT8,
}
pub type FWP_V6_ADDR_AND_MASK = FWP_V6_ADDR_AND_MASK_;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FWP_RANGE0_ {
    pub valueLow: FWP_VALUE0,
    pub valueHigh: FWP_VALUE0,
}
pub type FWP_RANGE0 = FWP_RANGE0_;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FWP_CONDITION_VALUE0_ {
    pub type_: FWP_DATA_TYPE,
    pub __bindgen_anon_1: FWP_CONDITION_VALUE0___bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FWP_CONDITION_VALUE0___bindgen_ty_1 {
    pub uint8: UINT8,
    pub uint16: UINT16,
    pub uint32: UINT32,
    pub uint64: *mut UINT64,
    pub int8: INT8,
    pub int16: INT16,
    pub int32: INT32,
    pub int64: *mut INT64,
    pub float32: f32,
    pub double64: *mut f64,
    pub byteArray16: *mut FWP_BYTE_ARRAY16,
    pub byteBlob: *mut FWP_BYTE_BLOB,
    pub sid: *mut SID,
    pub sd: *mut FWP_BYTE_BLOB,
    pub tokenInformation: *mut FWP_TOKEN_INFORMATION,
    pub tokenAccessInformation: *mut FWP_BYTE_BLOB,
    pub unicodeString: LPWSTR,
    pub byteArray6: *mut FWP_BYTE_ARRAY6,
    pub v4AddrMask: *mut FWP_V4_ADDR_AND_MASK,
    pub v6AddrMask: *mut FWP_V6_ADDR_AND_MASK,
    pub rangeValue: *mut FWP_RANGE0,
}
pub type FWP_CONDITION_VALUE0 = FWP_CONDITION_VALUE0_;
pub type FWPM_FILTER0 = FWPM_FILTER0_;
pub const FWPM_PROVIDER_CONTEXT_TYPE__FWPM_IPSEC_KEYING_CONTEXT: FWPM_PROVIDER_CONTEXT_TYPE_ = 0;
pub const FWPM_PROVIDER_CONTEXT_TYPE__FWPM_IPSEC_IKE_QM_TRANSPORT_CONTEXT:
    FWPM_PROVIDER_CONTEXT_TYPE_ = 1;
pub const FWPM_PROVIDER_CONTEXT_TYPE__FWPM_IPSEC_IKE_QM_TUNNEL_CONTEXT:
    FWPM_PROVIDER_CONTEXT_TYPE_ = 2;
pub const FWPM_PROVIDER_CONTEXT_TYPE__FWPM_IPSEC_AUTHIP_QM_TRANSPORT_CONTEXT:
    FWPM_PROVIDER_CONTEXT_TYPE_ = 3;
pub const FWPM_PROVIDER_CONTEXT_TYPE__FWPM_IPSEC_AUTHIP_QM_TUNNEL_CONTEXT:
    FWPM_PROVIDER_CONTEXT_TYPE_ = 4;
pub const FWPM_PROVIDER_CONTEXT_TYPE__FWPM_IPSEC_IKE_MM_CONTEXT: FWPM_PROVIDER_CONTEXT_TYPE_ = 5;
pub const FWPM_PROVIDER_CONTEXT_TYPE__FWPM_IPSEC_AUTHIP_MM_CONTEXT: FWPM_PROVIDER_CONTEXT_TYPE_ = 6;
pub const FWPM_PROVIDER_CONTEXT_TYPE__FWPM_CLASSIFY_OPTIONS_CONTEXT: FWPM_PROVIDER_CONTEXT_TYPE_ =
    7;
pub const FWPM_PROVIDER_CONTEXT_TYPE__FWPM_GENERAL_CONTEXT: FWPM_PROVIDER_CONTEXT_TYPE_ = 8;
pub const FWPM_PROVIDER_CONTEXT_TYPE__FWPM_IPSEC_IKEV2_QM_TUNNEL_CONTEXT:
    FWPM_PROVIDER_CONTEXT_TYPE_ = 9;
pub const FWPM_PROVIDER_CONTEXT_TYPE__FWPM_IPSEC_IKEV2_MM_CONTEXT: FWPM_PROVIDER_CONTEXT_TYPE_ = 10;
pub const FWPM_PROVIDER_CONTEXT_TYPE__FWPM_DOSP_CONTEXT: FWPM_PROVIDER_CONTEXT_TYPE_ = 11;
pub const FWPM_PROVIDER_CONTEXT_TYPE__FWPM_PROVIDER_CONTEXT_TYPE_MAX: FWPM_PROVIDER_CONTEXT_TYPE_ =
    12;
pub type FWPM_PROVIDER_CONTEXT_TYPE_ = ::std::os::raw::c_uint;
pub use self::FWPM_PROVIDER_CONTEXT_TYPE_ as FWPM_PROVIDER_CONTEXT_TYPE;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FWPM_ACTION0_ {
    pub type_: FWP_ACTION_TYPE,
    pub __bindgen_anon_1: FWPM_ACTION0___bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FWPM_ACTION0___bindgen_ty_1 {
    pub filterType: GUID,
    pub calloutKey: GUID,
}
pub type FWPM_ACTION0 = FWPM_ACTION0_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FWPM_DISPLAY_DATA0_ {
    pub name: *mut wchar_t,
    pub description: *mut wchar_t,
}
pub type FWPM_DISPLAY_DATA0 = FWPM_DISPLAY_DATA0_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FWPM_SESSION0_ {
    pub sessionKey: GUID,
    pub displayData: FWPM_DISPLAY_DATA0,
    pub flags: UINT32,
    pub txnWaitTimeoutInMSec: UINT32,
    pub processId: DWORD,
    pub sid: *mut SID,
    pub username: *mut wchar_t,
    pub kernelMode: WINBOOL,
}
pub type FWPM_SESSION0 = FWPM_SESSION0_;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FWPM_FILTER_CONDITION0_ {
    pub fieldKey: GUID,
    pub matchType: FWP_MATCH_TYPE,
    pub conditionValue: FWP_CONDITION_VALUE0,
}
pub type FWPM_FILTER_CONDITION0 = FWPM_FILTER_CONDITION0_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FWPM_PROVIDER_CONTEXT_ENUM_TEMPLATE0_ {
    pub providerKey: *mut GUID,
    pub providerContextType: FWPM_PROVIDER_CONTEXT_TYPE,
}
pub type FWPM_PROVIDER_CONTEXT_ENUM_TEMPLATE0 = FWPM_PROVIDER_CONTEXT_ENUM_TEMPLATE0_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FWPM_FILTER_ENUM_TEMPLATE0_ {
    pub providerKey: *mut GUID,
    pub layerKey: GUID,
    pub enumType: FWP_FILTER_ENUM_TYPE,
    pub flags: UINT32,
    pub providerContextTemplate: *mut FWPM_PROVIDER_CONTEXT_ENUM_TEMPLATE0,
    pub numFilterConditions: UINT32,
    pub filterCondition: *mut FWPM_FILTER_CONDITION0,
    pub actionMask: UINT32,
    pub calloutKey: *mut GUID,
}
pub type FWPM_FILTER_ENUM_TEMPLATE0 = FWPM_FILTER_ENUM_TEMPLATE0_;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FWPM_FILTER0_ {
    pub filterKey: GUID,
    pub displayData: FWPM_DISPLAY_DATA0,
    pub flags: UINT32,
    pub providerKey: *mut GUID,
    pub providerData: FWP_BYTE_BLOB,
    pub layerKey: GUID,
    pub subLayerKey: GUID,
    pub weight: FWP_VALUE0,
    pub numFilterConditions: UINT32,
    pub filterCondition: *mut FWPM_FILTER_CONDITION0,
    pub action: FWPM_ACTION0,
    pub __bindgen_anon_1: FWPM_FILTER0___bindgen_ty_1,
    pub reserved: *mut GUID,
    pub filterId: UINT64,
    pub effectiveWeight: FWP_VALUE0,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FWPM_FILTER0___bindgen_ty_1 {
    pub rawContext: UINT64,
    pub providerContextKey: GUID,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FWPM_PROVIDER0_ {
    pub providerKey: GUID,
    pub displayData: FWPM_DISPLAY_DATA0,
    pub flags: UINT32,
    pub providerData: FWP_BYTE_BLOB,
    pub serviceName: *mut wchar_t,
}
pub type FWPM_PROVIDER0 = FWPM_PROVIDER0_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FWPM_SUBLAYER0_ {
    pub subLayerKey: GUID,
    pub displayData: FWPM_DISPLAY_DATA0,
    pub flags: UINT16,
    pub providerKey: *mut GUID,
    pub providerData: FWP_BYTE_BLOB,
    pub weight: UINT16,
}
pub type FWPM_SUBLAYER0 = FWPM_SUBLAYER0_;
extern "stdcall" {
    pub fn FwpmEngineOpen0(
        serverName: *const wchar_t,
        authnService: UINT32,
        authIdentity: *mut SEC_WINNT_AUTH_IDENTITY_W,
        session: *const FWPM_SESSION0,
        engineHandle: *mut HANDLE,
    ) -> DWORD;
}
extern "stdcall" {
    pub fn FwpmFilterAdd0(
        engineHandle: HANDLE,
        filter: *const FWPM_FILTER0,
        sd: PSECURITY_DESCRIPTOR,
        id: *mut UINT64,
    ) -> DWORD;
}
extern "stdcall" {
    pub fn FwpmEngineClose0(engineHandle: HANDLE) -> DWORD;
}
extern "stdcall" {
    pub fn FwpmSubLayerAdd0(
        engineHandle: HANDLE,
        subLayer: *const FWPM_SUBLAYER0,
        sd: PSECURITY_DESCRIPTOR,
    ) -> DWORD;
}
extern "stdcall" {
    pub fn FwpmFreeMemory0(p: *mut *mut ::std::os::raw::c_void);
}
extern "stdcall" {
    pub fn FwpmFilterCreateEnumHandle0(
        engineHandle: HANDLE,
        enumTemplate: *const FWPM_FILTER_ENUM_TEMPLATE0,
        enumHandle: *mut HANDLE,
    ) -> DWORD;
}
extern "stdcall" {
    pub fn FwpmFilterDeleteById0(engineHandle: HANDLE, id: UINT64) -> DWORD;
}
extern "stdcall" {
    pub fn FwpmFilterDestroyEnumHandle0(engineHandle: HANDLE, enumHandle: HANDLE) -> DWORD;
}
extern "stdcall" {
    pub fn FwpmFilterEnum0(
        engineHandle: HANDLE,
        enumHandle: HANDLE,
        numEntriesRequested: UINT32,
        entries: *mut *mut *mut FWPM_FILTER0,
        numEntriesReturned: *mut UINT32,
    ) -> DWORD;
}
extern "stdcall" {
    pub fn FwpmProviderAdd0(
        engineHandle: HANDLE,
        provider: *const FWPM_PROVIDER0,
        sd: PSECURITY_DESCRIPTOR,
    ) -> DWORD;
}
extern "stdcall" {
    pub fn FwpmProviderDeleteByKey0(engineHandle: HANDLE, key: *const GUID) -> DWORD;
}
extern "stdcall" {
    pub fn FwpmProviderGetByKey0(
        engineHandle: HANDLE,
        key: *const GUID,
        provider: *mut *mut FWPM_PROVIDER0,
    ) -> DWORD;
}
extern "stdcall" {
    pub fn FwpmSubLayerDeleteByKey0(engineHandle: HANDLE, key: *const GUID) -> DWORD;
}
extern "stdcall" {
    pub fn FwpmTransactionBegin0(engineHandle: HANDLE, flags: UINT32) -> DWORD;
}
